// Direct /mobile/orders helper — bypasses BOTH:
//
//   1. imperialPerps.js:254 `SUPPORTED_OPEN_VENUES = {gmtrade, jupiter}` gate
//      (which rejects phoenix/flash_trade opens before the body is even built)
//   2. imperial.js:placeOrder()'s `routingMode === 'live'` precondition
//      (which would otherwise require setting IMPERIAL_ROUTING_MODE=live)
//
// We POST directly to /mobile/orders using the body shape proven by the
// OpenAPI spec (see imperial-order-protocol.ts). This lets us prove whether
// phoenix and flash_trade fills work AGAINST THE ACTUAL API without
// touching keeper code.
//
// Verification path mirrors what production does: poll /positions for a
// fresh open + check profile USDC drained (refund detection).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { authenticate, getMarkPrice } from "../../../keeper/src/imperial.js";
import { config } from "../../../keeper/src/config.js";
import {
  buildMarketOrderBody,
  buildCloseOrderBody,
  registerPhoenixProfile,
  type MobileOrderResponse,
  type VenueStr,
} from "./imperial-order-protocol.js";
import type { LiveAuth } from "./auth.js";

// Every /mobile/orders POST is appended here as a pretty-printed entry in a
// JSON array so the operator can hand a clean artifact to the Imperial dev
// when an order silently no-ops.
// Each entry: { ts, path, status, requestBody, responseBody, responseHeaders }
const DEBUG_PATH = resolve(process.cwd(), "test/live/imperial-debug.jsonl");
const DEBUG_HEADER =
  "# Imperial /mobile/orders request+response log (pretty-printed JSON array).\n" +
  "# Generated by test/live/helpers/direct-order.ts. One element per request.\n" +
  "# Hand this file to the Imperial dev when an order silently no-ops — every\n" +
  "# field they need is captured: request body, response body, response headers,\n" +
  "# status code, Solana signature (when filled).\n";

function readDebugEntries(): Record<string, unknown>[] {
  if (!existsSync(DEBUG_PATH)) return [];
  const raw = readFileSync(DEBUG_PATH, "utf8");
  // Strip leading `#` comment lines, then parse the rest as JSON.
  const body = raw
    .split(/\r?\n/)
    .filter((l) => !l.trimStart().startsWith("#"))
    .join("\n")
    .trim();
  if (!body) return [];
  try {
    const parsed = JSON.parse(body);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    // Legacy JSONL fallback — one JSON object per line.
    return raw
      .split(/\r?\n/)
      .filter((l) => l.trim() && !l.trimStart().startsWith("#"))
      .map((l) => {
        try {
          return JSON.parse(l);
        } catch {
          return null;
        }
      })
      .filter((x): x is Record<string, unknown> => x !== null);
  }
}

function appendDebug(entry: Record<string, unknown>): void {
  const entries = readDebugEntries();
  entries.push(entry);
  writeFileSync(DEBUG_PATH, DEBUG_HEADER + JSON.stringify(entries, null, 2) + "\n", "utf8");
}

const IMPERIAL_BASE_URL =
  process.env.IMPERIAL_BASE_URL?.trim() || "https://api.imperial.space/api/v1";

function headers(token: string): Record<string, string> {
  // Match the working probe's auth pattern at
  // keeper/scripts/imperial-order-probe.mjs:53 — Imperial requires BOTH
  // `Authorization: Bearer <JWT>` AND `x-api-key`. When no dedicated API key
  // is configured we fall back to using the JWT itself as `x-api-key`. Without
  // this, /mobile/orders returns success:false with a generic "Failed to
  // place order" error (no 401) — confirmed via 4 reproductions on phoenix
  // and flash_trade before this fix.
  const apiKey = process.env.IMPERIAL_API_KEY?.trim() || config.imperial.apiKey;
  return {
    Authorization: `Bearer ${token}`,
    "x-api-key": apiKey || token,
    "Content-Type": "application/json",
  };
}

async function postJson<T = unknown>(path: string, token: string, body: unknown): Promise<T> {
  const res = await fetch(`${IMPERIAL_BASE_URL}${path}`, {
    method: "POST",
    headers: headers(token),
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let parsed: unknown;
  try {
    parsed = text ? JSON.parse(text) : {};
  } catch {
    parsed = { raw: text };
  }
  // Capture EVERY POST to /mobile/orders (the unreliable endpoint) for
  // debugging. Other paths (auth, register) are skipped — they're not the
  // ones with the silent-no-op problem.
  if (path.startsWith("/mobile/orders")) {
    const respHeaders: Record<string, string> = {};
    res.headers.forEach((v, k) => {
      respHeaders[k] = v;
    });
    appendDebug({
      ts: new Date().toISOString(),
      path,
      status: res.status,
      requestBody: body,
      responseBody: parsed,
      responseHeaders: respHeaders,
    });
    console.log(
      `[direct:debug] POST ${path} → status=${res.status} ` +
        `bodySize=${text.length}B logged to ${DEBUG_PATH}`,
    );
  }
  if (!res.ok) {
    throw new Error(
      `${path} ${res.status}: ${typeof parsed === "string" ? parsed : JSON.stringify(parsed)}`,
    );
  }
  return parsed as T;
}

// Re-authenticate every call so we don't depend on auth.ts's caching when
// the direct path is invoked from a separate flow.
export async function directAuth(kp: LiveAuth["kp"]): Promise<string> {
  const a = await authenticate(kp);
  if (!a?.token) throw new Error("directAuth: authenticate() returned no token");
  return a.token;
}

// Pre-activate phoenix for (wallet, profileIndex). Idempotent.
// Per the OpenAPI: /phoenix/register is optional — /mobile/orders
// auto-activates on first use. Calling this explicitly warms the cache
// and gives us a clean signal if activation itself fails (vs an order-
// level failure).
export async function directRegisterPhoenix(opts: {
  wallet: string;
  profileIndex: number;
}): Promise<{ activated: boolean; profilePda: string; message: string }> {
  return registerPhoenixProfile({
    baseUrl: IMPERIAL_BASE_URL,
    wallet: opts.wallet,
    profileIndex: opts.profileIndex,
  });
}

// Hit /route once before placing an order. The working probe at
// keeper/scripts/imperial-order-probe.mjs:79-88 always calls /route
// immediately before /mobile/orders, and the production keeper loop does
// the same via imperialQuoteIfEnabled. Imperial may keep per-(wallet,
// profile, asset, venue) server-side state populated by /route that
// /mobile/orders relies on — undocumented but worth probing as a hypothesis.
export async function directRouteWarm(opts: {
  wallet: string;
  profileIndex: number;
  symbol: string;
  side: "long" | "short";
  collateralUsd: number;
  leverage: number;
  // When set, exclude every venue NOT in this list so /route is FORCED to
  // pick the target venue. Use this when you want server-side state aligned
  // with a specific underwriter you're about to send.
  pinVenue?: VenueStr;
}): Promise<unknown> {
  const USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
  const notional = opts.collateralUsd * opts.leverage;
  const qs = new URLSearchParams({
    asset: opts.symbol.toUpperCase(),
    side: opts.side,
    amount: String(Math.round(opts.collateralUsd * 1_000_000)),
    collateralAsset: USDC,
    notional: notional.toFixed(6),
    desiredLeverage: String(opts.leverage),
    slippageBps: "100",
    wallet: opts.wallet,
    profileIndex: String(opts.profileIndex),
  });
  if (opts.pinVenue) {
    const allVenues: VenueStr[] = ["jupiter", "flash_trade", "phoenix", "gmtrade"];
    const excluded = allVenues.filter((v) => v !== opts.pinVenue);
    qs.set("excludedVenues", excluded.join(","));
  }
  const res = await fetch(`${IMPERIAL_BASE_URL}/route?${qs}`);
  if (!res.ok) {
    throw new Error(`/route ${res.status}: ${await res.text()}`);
  }
  return res.json();
}

// Fetch mark price in oracle scale (1e9). The keeper's getMarkPrice maps
// venue keys 1:1 to the API row keys, which works for phoenix/gmtrade but
// NOT flash_trade (API uses `flash` as the row key, not `flash_trade`).
// We try the keeper helper first; if it returns null for flash_trade we
// fall back to a direct /mark-prices fetch with the right key.
export async function directMarkPrice(symbol: string, venue: VenueStr): Promise<number | null> {
  const primary = await getMarkPrice(symbol, venue);
  if (primary !== null && primary !== undefined) return primary;

  // Fallback for flash_trade — the API row key is `flash` not `flash_trade`.
  if (venue === "flash_trade") {
    try {
      const res = await fetch(`${IMPERIAL_BASE_URL}/mark-prices`, {
        headers: config.imperial.apiKey ? { "x-api-key": config.imperial.apiKey } : {},
      });
      if (!res.ok) return null;
      const body = (await res.json()) as { rows?: Array<Record<string, unknown>> };
      const rows = body?.rows ?? [];
      const sym = symbol.toUpperCase();
      const row = rows.find((r) => String(r.symbol).toUpperCase() === sym);
      if (!row) return null;
      // Try a few likely shapes the API might use.
      const flash = row.flash as { price?: number } | undefined;
      const price = flash?.price ?? null;
      if (price === null || price === undefined) return null;
      return Math.round(Number(price) * 1_000_000_000);
    } catch {
      return null;
    }
  }
  return null;
}

// POST /mobile/orders with a Market-Increase body. The wallet's JWT must
// match `wallet`. Returns the raw Imperial response — note that
// `success: false` does NOT mean the order didn't fill (Imperial's
// /mobile/orders is famously unreliable; verify via /positions polling).
export async function directOpen(opts: {
  token: string;
  venue: VenueStr;
  wallet: string;
  symbol: string;
  side: "long" | "short";
  collateralUsd: number;
  sizeUsd: number;
  slippageBps?: number;
  profileIndex: number;
  marketPrice: number;
}): Promise<MobileOrderResponse> {
  const body = buildMarketOrderBody({
    venue: opts.venue,
    wallet: opts.wallet,
    symbol: opts.symbol,
    side: opts.side,
    collateralUsd: opts.collateralUsd,
    sizeUsd: opts.sizeUsd,
    slippageBps: opts.slippageBps,
    profileIndex: opts.profileIndex,
    marketPrice: opts.marketPrice,
  });
  return postJson<MobileOrderResponse>("/mobile/orders", opts.token, body);
}

// POST /mobile/orders with a Market-Decrease body. Same wrinkle as open —
// `success: false` is possible but the position may still have closed
// on-chain. Verify via /positions polling.
export async function directClose(opts: {
  token: string;
  venue: VenueStr;
  wallet: string;
  symbol: string;
  side: "long" | "short";
  closeSizeUsd: number; // for full close, pass exact position.sizeUsd
  slippageBps?: number;
  profileIndex: number;
  marketPrice: number;
  // Position PDA from /positions[*].positionPda — required for flash_trade.
  positionId?: string;
}): Promise<MobileOrderResponse> {
  const body = buildCloseOrderBody({
    venue: opts.venue,
    wallet: opts.wallet,
    symbol: opts.symbol,
    side: opts.side,
    closeSizeUsd: opts.closeSizeUsd,
    slippageBps: opts.slippageBps,
    profileIndex: opts.profileIndex,
    marketPrice: opts.marketPrice,
    positionId: opts.positionId,
  });
  return postJson<MobileOrderResponse>("/mobile/orders", opts.token, body);
}
