/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as RouteFeesRouteImport } from './routes/route-fees'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenIdRouteImport } from './routes/token.$id'
import { Route as RouteFeesClaimTokenRouteImport } from './routes/route-fees.$claimToken'
import { Route as ApiPublicSolanaRpcRouteImport } from './routes/api/public/solana/rpc'
import { Route as ApiPublicKeeperTokensRouteImport } from './routes/api/public/keeper/tokens'
import { Route as ApiPublicKeeperReportRouteImport } from './routes/api/public/keeper/report'
import { Route as ApiPublicKeeperExternalSweepReportRouteImport } from './routes/api/public/keeper/external-sweep-report'
import { Route as ApiPublicKeeperExternalRoutersRouteImport } from './routes/api/public/keeper/external-routers'
import { Route as ApiPublicKeeperExternalRouterSeenRouteImport } from './routes/api/public/keeper/external-router-seen'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteFeesRoute = RouteFeesRouteImport.update({
  id: '/route-fees',
  path: '/route-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIdRoute = TokenIdRouteImport.update({
  id: '/token/$id',
  path: '/token/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteFeesClaimTokenRoute = RouteFeesClaimTokenRouteImport.update({
  id: '/$claimToken',
  path: '/$claimToken',
  getParentRoute: () => RouteFeesRoute,
} as any)
const ApiPublicSolanaRpcRoute = ApiPublicSolanaRpcRouteImport.update({
  id: '/api/public/solana/rpc',
  path: '/api/public/solana/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperTokensRoute = ApiPublicKeeperTokensRouteImport.update({
  id: '/api/public/keeper/tokens',
  path: '/api/public/keeper/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperReportRoute = ApiPublicKeeperReportRouteImport.update({
  id: '/api/public/keeper/report',
  path: '/api/public/keeper/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperExternalSweepReportRoute =
  ApiPublicKeeperExternalSweepReportRouteImport.update({
    id: '/api/public/keeper/external-sweep-report',
    path: '/api/public/keeper/external-sweep-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperExternalRoutersRoute =
  ApiPublicKeeperExternalRoutersRouteImport.update({
    id: '/api/public/keeper/external-routers',
    path: '/api/public/keeper/external-routers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperExternalRouterSeenRoute =
  ApiPublicKeeperExternalRouterSeenRouteImport.update({
    id: '/api/public/keeper/external-router-seen',
    path: '/api/public/keeper/external-router-seen',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/launch': typeof LaunchRoute
  '/paper': typeof PaperRoute
  '/route-fees': typeof RouteFeesRouteWithChildren
  '/tokens': typeof TokensRoute
  '/route-fees/$claimToken': typeof RouteFeesClaimTokenRoute
  '/token/$id': typeof TokenIdRoute
  '/api/public/keeper/external-router-seen': typeof ApiPublicKeeperExternalRouterSeenRoute
  '/api/public/keeper/external-routers': typeof ApiPublicKeeperExternalRoutersRoute
  '/api/public/keeper/external-sweep-report': typeof ApiPublicKeeperExternalSweepReportRoute
  '/api/public/keeper/report': typeof ApiPublicKeeperReportRoute
  '/api/public/keeper/tokens': typeof ApiPublicKeeperTokensRoute
  '/api/public/solana/rpc': typeof ApiPublicSolanaRpcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/launch': typeof LaunchRoute
  '/paper': typeof PaperRoute
  '/route-fees': typeof RouteFeesRouteWithChildren
  '/tokens': typeof TokensRoute
  '/route-fees/$claimToken': typeof RouteFeesClaimTokenRoute
  '/token/$id': typeof TokenIdRoute
  '/api/public/keeper/external-router-seen': typeof ApiPublicKeeperExternalRouterSeenRoute
  '/api/public/keeper/external-routers': typeof ApiPublicKeeperExternalRoutersRoute
  '/api/public/keeper/external-sweep-report': typeof ApiPublicKeeperExternalSweepReportRoute
  '/api/public/keeper/report': typeof ApiPublicKeeperReportRoute
  '/api/public/keeper/tokens': typeof ApiPublicKeeperTokensRoute
  '/api/public/solana/rpc': typeof ApiPublicSolanaRpcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/launch': typeof LaunchRoute
  '/paper': typeof PaperRoute
  '/route-fees': typeof RouteFeesRouteWithChildren
  '/tokens': typeof TokensRoute
  '/route-fees/$claimToken': typeof RouteFeesClaimTokenRoute
  '/token/$id': typeof TokenIdRoute
  '/api/public/keeper/external-router-seen': typeof ApiPublicKeeperExternalRouterSeenRoute
  '/api/public/keeper/external-routers': typeof ApiPublicKeeperExternalRoutersRoute
  '/api/public/keeper/external-sweep-report': typeof ApiPublicKeeperExternalSweepReportRoute
  '/api/public/keeper/report': typeof ApiPublicKeeperReportRoute
  '/api/public/keeper/tokens': typeof ApiPublicKeeperTokensRoute
  '/api/public/solana/rpc': typeof ApiPublicSolanaRpcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/home'
    | '/launch'
    | '/paper'
    | '/route-fees'
    | '/tokens'
    | '/route-fees/$claimToken'
    | '/token/$id'
    | '/api/public/keeper/external-router-seen'
    | '/api/public/keeper/external-routers'
    | '/api/public/keeper/external-sweep-report'
    | '/api/public/keeper/report'
    | '/api/public/keeper/tokens'
    | '/api/public/solana/rpc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/home'
    | '/launch'
    | '/paper'
    | '/route-fees'
    | '/tokens'
    | '/route-fees/$claimToken'
    | '/token/$id'
    | '/api/public/keeper/external-router-seen'
    | '/api/public/keeper/external-routers'
    | '/api/public/keeper/external-sweep-report'
    | '/api/public/keeper/report'
    | '/api/public/keeper/tokens'
    | '/api/public/solana/rpc'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/home'
    | '/launch'
    | '/paper'
    | '/route-fees'
    | '/tokens'
    | '/route-fees/$claimToken'
    | '/token/$id'
    | '/api/public/keeper/external-router-seen'
    | '/api/public/keeper/external-routers'
    | '/api/public/keeper/external-sweep-report'
    | '/api/public/keeper/report'
    | '/api/public/keeper/tokens'
    | '/api/public/solana/rpc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  HomeRoute: typeof HomeRoute
  LaunchRoute: typeof LaunchRoute
  PaperRoute: typeof PaperRoute
  RouteFeesRoute: typeof RouteFeesRouteWithChildren
  TokensRoute: typeof TokensRoute
  TokenIdRoute: typeof TokenIdRoute
  ApiPublicKeeperExternalRouterSeenRoute: typeof ApiPublicKeeperExternalRouterSeenRoute
  ApiPublicKeeperExternalRoutersRoute: typeof ApiPublicKeeperExternalRoutersRoute
  ApiPublicKeeperExternalSweepReportRoute: typeof ApiPublicKeeperExternalSweepReportRoute
  ApiPublicKeeperReportRoute: typeof ApiPublicKeeperReportRoute
  ApiPublicKeeperTokensRoute: typeof ApiPublicKeeperTokensRoute
  ApiPublicSolanaRpcRoute: typeof ApiPublicSolanaRpcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-fees': {
      id: '/route-fees'
      path: '/route-fees'
      fullPath: '/route-fees'
      preLoaderRoute: typeof RouteFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$id': {
      id: '/token/$id'
      path: '/token/$id'
      fullPath: '/token/$id'
      preLoaderRoute: typeof TokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-fees/$claimToken': {
      id: '/route-fees/$claimToken'
      path: '/$claimToken'
      fullPath: '/route-fees/$claimToken'
      preLoaderRoute: typeof RouteFeesClaimTokenRouteImport
      parentRoute: typeof RouteFeesRoute
    }
    '/api/public/solana/rpc': {
      id: '/api/public/solana/rpc'
      path: '/api/public/solana/rpc'
      fullPath: '/api/public/solana/rpc'
      preLoaderRoute: typeof ApiPublicSolanaRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/tokens': {
      id: '/api/public/keeper/tokens'
      path: '/api/public/keeper/tokens'
      fullPath: '/api/public/keeper/tokens'
      preLoaderRoute: typeof ApiPublicKeeperTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/report': {
      id: '/api/public/keeper/report'
      path: '/api/public/keeper/report'
      fullPath: '/api/public/keeper/report'
      preLoaderRoute: typeof ApiPublicKeeperReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/external-sweep-report': {
      id: '/api/public/keeper/external-sweep-report'
      path: '/api/public/keeper/external-sweep-report'
      fullPath: '/api/public/keeper/external-sweep-report'
      preLoaderRoute: typeof ApiPublicKeeperExternalSweepReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/external-routers': {
      id: '/api/public/keeper/external-routers'
      path: '/api/public/keeper/external-routers'
      fullPath: '/api/public/keeper/external-routers'
      preLoaderRoute: typeof ApiPublicKeeperExternalRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/external-router-seen': {
      id: '/api/public/keeper/external-router-seen'
      path: '/api/public/keeper/external-router-seen'
      fullPath: '/api/public/keeper/external-router-seen'
      preLoaderRoute: typeof ApiPublicKeeperExternalRouterSeenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RouteFeesRouteChildren {
  RouteFeesClaimTokenRoute: typeof RouteFeesClaimTokenRoute
}

const RouteFeesRouteChildren: RouteFeesRouteChildren = {
  RouteFeesClaimTokenRoute: RouteFeesClaimTokenRoute,
}

const RouteFeesRouteWithChildren = RouteFeesRoute._addFileChildren(
  RouteFeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  HomeRoute: HomeRoute,
  LaunchRoute: LaunchRoute,
  PaperRoute: PaperRoute,
  RouteFeesRoute: RouteFeesRouteWithChildren,
  TokensRoute: TokensRoute,
  TokenIdRoute: TokenIdRoute,
  ApiPublicKeeperExternalRouterSeenRoute:
    ApiPublicKeeperExternalRouterSeenRoute,
  ApiPublicKeeperExternalRoutersRoute: ApiPublicKeeperExternalRoutersRoute,
  ApiPublicKeeperExternalSweepReportRoute:
    ApiPublicKeeperExternalSweepReportRoute,
  ApiPublicKeeperReportRoute: ApiPublicKeeperReportRoute,
  ApiPublicKeeperTokensRoute: ApiPublicKeeperTokensRoute,
  ApiPublicSolanaRpcRoute: ApiPublicSolanaRpcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
