/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RouteFeesRouteImport } from './routes/route-fees'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenIdRouteImport } from './routes/token.$id'
import { Route as RouteFeesClaimTokenRouteImport } from './routes/route-fees.$claimToken'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminKeeperLogsRouteImport } from './routes/admin.keeper-logs'
import { Route as ApiV1OpenapiRouteImport } from './routes/api/v1/openapi'
import { Route as ApiV1MarketsRouteImport } from './routes/api/v1/markets'
import { Route as ApiV1LaunchRouteImport } from './routes/api/v1/launch'
import { Route as ApiAdminReconcileLaunchesRouteImport } from './routes/api/admin/reconcile-launches'
import { Route as AdminLogsTokenIdRouteImport } from './routes/admin.logs_.$tokenId'
import { Route as AdminKeeperLogsTokenIdRouteImport } from './routes/admin.keeper-logs_.$tokenId'
import { Route as ApiV1LaunchTokenIdRouteImport } from './routes/api/v1/launch.$tokenId'
import { Route as ApiPublicSolanaRpcRouteImport } from './routes/api/public/solana/rpc'
import { Route as ApiPublicKeeperWorkflowsRouteImport } from './routes/api/public/keeper/workflows'
import { Route as ApiPublicKeeperWorkflowReportRouteImport } from './routes/api/public/keeper/workflow-report'
import { Route as ApiPublicKeeperWorkflowLocksRouteImport } from './routes/api/public/keeper/workflow-locks'
import { Route as ApiPublicKeeperTokensRouteImport } from './routes/api/public/keeper/tokens'
import { Route as ApiPublicKeeperStuckTokensRouteImport } from './routes/api/public/keeper/stuck-tokens'
import { Route as ApiPublicKeeperReportRouteImport } from './routes/api/public/keeper/report'
import { Route as ApiPublicKeeperLogsRouteImport } from './routes/api/public/keeper/logs'
import { Route as ApiPublicKeeperExternalSweepReportRouteImport } from './routes/api/public/keeper/external-sweep-report'
import { Route as ApiPublicKeeperExternalRoutersRouteImport } from './routes/api/public/keeper/external-routers'
import { Route as ApiPublicKeeperExternalRouterSeenRouteImport } from './routes/api/public/keeper/external-router-seen'
import { Route as ApiV1LaunchTokenIdMetadataRouteImport } from './routes/api/v1/launch.$tokenId.metadata'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteFeesRoute = RouteFeesRouteImport.update({
  id: '/route-fees',
  path: '/route-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIdRoute = TokenIdRouteImport.update({
  id: '/token/$id',
  path: '/token/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteFeesClaimTokenRoute = RouteFeesClaimTokenRouteImport.update({
  id: '/$claimToken',
  path: '/$claimToken',
  getParentRoute: () => RouteFeesRoute,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeeperLogsRoute = AdminKeeperLogsRouteImport.update({
  id: '/admin/keeper-logs',
  path: '/admin/keeper-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiRoute = ApiV1OpenapiRouteImport.update({
  id: '/api/v1/openapi',
  path: '/api/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MarketsRoute = ApiV1MarketsRouteImport.update({
  id: '/api/v1/markets',
  path: '/api/v1/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LaunchRoute = ApiV1LaunchRouteImport.update({
  id: '/api/v1/launch',
  path: '/api/v1/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReconcileLaunchesRoute =
  ApiAdminReconcileLaunchesRouteImport.update({
    id: '/api/admin/reconcile-launches',
    path: '/api/admin/reconcile-launches',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLogsTokenIdRoute = AdminLogsTokenIdRouteImport.update({
  id: '/admin/logs_/$tokenId',
  path: '/admin/logs/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeeperLogsTokenIdRoute = AdminKeeperLogsTokenIdRouteImport.update({
  id: '/admin/keeper-logs_/$tokenId',
  path: '/admin/keeper-logs/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LaunchTokenIdRoute = ApiV1LaunchTokenIdRouteImport.update({
  id: '/$tokenId',
  path: '/$tokenId',
  getParentRoute: () => ApiV1LaunchRoute,
} as any)
const ApiPublicSolanaRpcRoute = ApiPublicSolanaRpcRouteImport.update({
  id: '/api/public/solana/rpc',
  path: '/api/public/solana/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperWorkflowsRoute =
  ApiPublicKeeperWorkflowsRouteImport.update({
    id: '/api/public/keeper/workflows',
    path: '/api/public/keeper/workflows',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperWorkflowReportRoute =
  ApiPublicKeeperWorkflowReportRouteImport.update({
    id: '/api/public/keeper/workflow-report',
    path: '/api/public/keeper/workflow-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperWorkflowLocksRoute =
  ApiPublicKeeperWorkflowLocksRouteImport.update({
    id: '/api/public/keeper/workflow-locks',
    path: '/api/public/keeper/workflow-locks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperTokensRoute = ApiPublicKeeperTokensRouteImport.update({
  id: '/api/public/keeper/tokens',
  path: '/api/public/keeper/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperStuckTokensRoute =
  ApiPublicKeeperStuckTokensRouteImport.update({
    id: '/api/public/keeper/stuck-tokens',
    path: '/api/public/keeper/stuck-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperReportRoute = ApiPublicKeeperReportRouteImport.update({
  id: '/api/public/keeper/report',
  path: '/api/public/keeper/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperLogsRoute = ApiPublicKeeperLogsRouteImport.update({
  id: '/api/public/keeper/logs',
  path: '/api/public/keeper/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeeperExternalSweepReportRoute =
  ApiPublicKeeperExternalSweepReportRouteImport.update({
    id: '/api/public/keeper/external-sweep-report',
    path: '/api/public/keeper/external-sweep-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperExternalRoutersRoute =
  ApiPublicKeeperExternalRoutersRouteImport.update({
    id: '/api/public/keeper/external-routers',
    path: '/api/public/keeper/external-routers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKeeperExternalRouterSeenRoute =
  ApiPublicKeeperExternalRouterSeenRouteImport.update({
    id: '/api/public/keeper/external-router-seen',
    path: '/api/public/keeper/external-router-seen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1LaunchTokenIdMetadataRoute =
  ApiV1LaunchTokenIdMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => ApiV1LaunchTokenIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/launch': typeof LaunchRoute
  '/paper': typeof PaperRoute
  '/route-fees': typeof RouteFeesRouteWithChildren
  '/stats': typeof StatsRoute
  '/tokens': typeof TokensRoute
  '/admin/keeper-logs': typeof AdminKeeperLogsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/docs': typeof ApiDocsRoute
  '/route-fees/$claimToken': typeof RouteFeesClaimTokenRoute
  '/token/$id': typeof TokenIdRoute
  '/admin/keeper-logs/$tokenId': typeof AdminKeeperLogsTokenIdRoute
  '/admin/logs/$tokenId': typeof AdminLogsTokenIdRoute
  '/api/admin/reconcile-launches': typeof ApiAdminReconcileLaunchesRoute
  '/api/v1/launch': typeof ApiV1LaunchRouteWithChildren
  '/api/v1/markets': typeof ApiV1MarketsRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/public/keeper/external-router-seen': typeof ApiPublicKeeperExternalRouterSeenRoute
  '/api/public/keeper/external-routers': typeof ApiPublicKeeperExternalRoutersRoute
  '/api/public/keeper/external-sweep-report': typeof ApiPublicKeeperExternalSweepReportRoute
  '/api/public/keeper/logs': typeof ApiPublicKeeperLogsRoute
  '/api/public/keeper/report': typeof ApiPublicKeeperReportRoute
  '/api/public/keeper/stuck-tokens': typeof ApiPublicKeeperStuckTokensRoute
  '/api/public/keeper/tokens': typeof ApiPublicKeeperTokensRoute
  '/api/public/keeper/workflow-locks': typeof ApiPublicKeeperWorkflowLocksRoute
  '/api/public/keeper/workflow-report': typeof ApiPublicKeeperWorkflowReportRoute
  '/api/public/keeper/workflows': typeof ApiPublicKeeperWorkflowsRoute
  '/api/public/solana/rpc': typeof ApiPublicSolanaRpcRoute
  '/api/v1/launch/$tokenId': typeof ApiV1LaunchTokenIdRouteWithChildren
  '/api/v1/launch/$tokenId/metadata': typeof ApiV1LaunchTokenIdMetadataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/launch': typeof LaunchRoute
  '/paper': typeof PaperRoute
  '/route-fees': typeof RouteFeesRouteWithChildren
  '/stats': typeof StatsRoute
  '/tokens': typeof TokensRoute
  '/admin/keeper-logs': typeof AdminKeeperLogsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/docs': typeof ApiDocsRoute
  '/route-fees/$claimToken': typeof RouteFeesClaimTokenRoute
  '/token/$id': typeof TokenIdRoute
  '/admin/keeper-logs/$tokenId': typeof AdminKeeperLogsTokenIdRoute
  '/admin/logs/$tokenId': typeof AdminLogsTokenIdRoute
  '/api/admin/reconcile-launches': typeof ApiAdminReconcileLaunchesRoute
  '/api/v1/launch': typeof ApiV1LaunchRouteWithChildren
  '/api/v1/markets': typeof ApiV1MarketsRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/public/keeper/external-router-seen': typeof ApiPublicKeeperExternalRouterSeenRoute
  '/api/public/keeper/external-routers': typeof ApiPublicKeeperExternalRoutersRoute
  '/api/public/keeper/external-sweep-report': typeof ApiPublicKeeperExternalSweepReportRoute
  '/api/public/keeper/logs': typeof ApiPublicKeeperLogsRoute
  '/api/public/keeper/report': typeof ApiPublicKeeperReportRoute
  '/api/public/keeper/stuck-tokens': typeof ApiPublicKeeperStuckTokensRoute
  '/api/public/keeper/tokens': typeof ApiPublicKeeperTokensRoute
  '/api/public/keeper/workflow-locks': typeof ApiPublicKeeperWorkflowLocksRoute
  '/api/public/keeper/workflow-report': typeof ApiPublicKeeperWorkflowReportRoute
  '/api/public/keeper/workflows': typeof ApiPublicKeeperWorkflowsRoute
  '/api/public/solana/rpc': typeof ApiPublicSolanaRpcRoute
  '/api/v1/launch/$tokenId': typeof ApiV1LaunchTokenIdRouteWithChildren
  '/api/v1/launch/$tokenId/metadata': typeof ApiV1LaunchTokenIdMetadataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/launch': typeof LaunchRoute
  '/paper': typeof PaperRoute
  '/route-fees': typeof RouteFeesRouteWithChildren
  '/stats': typeof StatsRoute
  '/tokens': typeof TokensRoute
  '/admin/keeper-logs': typeof AdminKeeperLogsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/docs': typeof ApiDocsRoute
  '/route-fees/$claimToken': typeof RouteFeesClaimTokenRoute
  '/token/$id': typeof TokenIdRoute
  '/admin/keeper-logs_/$tokenId': typeof AdminKeeperLogsTokenIdRoute
  '/admin/logs_/$tokenId': typeof AdminLogsTokenIdRoute
  '/api/admin/reconcile-launches': typeof ApiAdminReconcileLaunchesRoute
  '/api/v1/launch': typeof ApiV1LaunchRouteWithChildren
  '/api/v1/markets': typeof ApiV1MarketsRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/public/keeper/external-router-seen': typeof ApiPublicKeeperExternalRouterSeenRoute
  '/api/public/keeper/external-routers': typeof ApiPublicKeeperExternalRoutersRoute
  '/api/public/keeper/external-sweep-report': typeof ApiPublicKeeperExternalSweepReportRoute
  '/api/public/keeper/logs': typeof ApiPublicKeeperLogsRoute
  '/api/public/keeper/report': typeof ApiPublicKeeperReportRoute
  '/api/public/keeper/stuck-tokens': typeof ApiPublicKeeperStuckTokensRoute
  '/api/public/keeper/tokens': typeof ApiPublicKeeperTokensRoute
  '/api/public/keeper/workflow-locks': typeof ApiPublicKeeperWorkflowLocksRoute
  '/api/public/keeper/workflow-report': typeof ApiPublicKeeperWorkflowReportRoute
  '/api/public/keeper/workflows': typeof ApiPublicKeeperWorkflowsRoute
  '/api/public/solana/rpc': typeof ApiPublicSolanaRpcRoute
  '/api/v1/launch/$tokenId': typeof ApiV1LaunchTokenIdRouteWithChildren
  '/api/v1/launch/$tokenId/metadata': typeof ApiV1LaunchTokenIdMetadataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/docs'
    | '/home'
    | '/launch'
    | '/paper'
    | '/route-fees'
    | '/stats'
    | '/tokens'
    | '/admin/keeper-logs'
    | '/admin/logs'
    | '/api/docs'
    | '/route-fees/$claimToken'
    | '/token/$id'
    | '/admin/keeper-logs/$tokenId'
    | '/admin/logs/$tokenId'
    | '/api/admin/reconcile-launches'
    | '/api/v1/launch'
    | '/api/v1/markets'
    | '/api/v1/openapi'
    | '/api/public/keeper/external-router-seen'
    | '/api/public/keeper/external-routers'
    | '/api/public/keeper/external-sweep-report'
    | '/api/public/keeper/logs'
    | '/api/public/keeper/report'
    | '/api/public/keeper/stuck-tokens'
    | '/api/public/keeper/tokens'
    | '/api/public/keeper/workflow-locks'
    | '/api/public/keeper/workflow-report'
    | '/api/public/keeper/workflows'
    | '/api/public/solana/rpc'
    | '/api/v1/launch/$tokenId'
    | '/api/v1/launch/$tokenId/metadata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/docs'
    | '/home'
    | '/launch'
    | '/paper'
    | '/route-fees'
    | '/stats'
    | '/tokens'
    | '/admin/keeper-logs'
    | '/admin/logs'
    | '/api/docs'
    | '/route-fees/$claimToken'
    | '/token/$id'
    | '/admin/keeper-logs/$tokenId'
    | '/admin/logs/$tokenId'
    | '/api/admin/reconcile-launches'
    | '/api/v1/launch'
    | '/api/v1/markets'
    | '/api/v1/openapi'
    | '/api/public/keeper/external-router-seen'
    | '/api/public/keeper/external-routers'
    | '/api/public/keeper/external-sweep-report'
    | '/api/public/keeper/logs'
    | '/api/public/keeper/report'
    | '/api/public/keeper/stuck-tokens'
    | '/api/public/keeper/tokens'
    | '/api/public/keeper/workflow-locks'
    | '/api/public/keeper/workflow-report'
    | '/api/public/keeper/workflows'
    | '/api/public/solana/rpc'
    | '/api/v1/launch/$tokenId'
    | '/api/v1/launch/$tokenId/metadata'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/docs'
    | '/home'
    | '/launch'
    | '/paper'
    | '/route-fees'
    | '/stats'
    | '/tokens'
    | '/admin/keeper-logs'
    | '/admin/logs'
    | '/api/docs'
    | '/route-fees/$claimToken'
    | '/token/$id'
    | '/admin/keeper-logs_/$tokenId'
    | '/admin/logs_/$tokenId'
    | '/api/admin/reconcile-launches'
    | '/api/v1/launch'
    | '/api/v1/markets'
    | '/api/v1/openapi'
    | '/api/public/keeper/external-router-seen'
    | '/api/public/keeper/external-routers'
    | '/api/public/keeper/external-sweep-report'
    | '/api/public/keeper/logs'
    | '/api/public/keeper/report'
    | '/api/public/keeper/stuck-tokens'
    | '/api/public/keeper/tokens'
    | '/api/public/keeper/workflow-locks'
    | '/api/public/keeper/workflow-report'
    | '/api/public/keeper/workflows'
    | '/api/public/solana/rpc'
    | '/api/v1/launch/$tokenId'
    | '/api/v1/launch/$tokenId/metadata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  DocsRoute: typeof DocsRoute
  HomeRoute: typeof HomeRoute
  LaunchRoute: typeof LaunchRoute
  PaperRoute: typeof PaperRoute
  RouteFeesRoute: typeof RouteFeesRouteWithChildren
  StatsRoute: typeof StatsRoute
  TokensRoute: typeof TokensRoute
  AdminKeeperLogsRoute: typeof AdminKeeperLogsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  TokenIdRoute: typeof TokenIdRoute
  AdminKeeperLogsTokenIdRoute: typeof AdminKeeperLogsTokenIdRoute
  AdminLogsTokenIdRoute: typeof AdminLogsTokenIdRoute
  ApiAdminReconcileLaunchesRoute: typeof ApiAdminReconcileLaunchesRoute
  ApiV1LaunchRoute: typeof ApiV1LaunchRouteWithChildren
  ApiV1MarketsRoute: typeof ApiV1MarketsRoute
  ApiV1OpenapiRoute: typeof ApiV1OpenapiRoute
  ApiPublicKeeperExternalRouterSeenRoute: typeof ApiPublicKeeperExternalRouterSeenRoute
  ApiPublicKeeperExternalRoutersRoute: typeof ApiPublicKeeperExternalRoutersRoute
  ApiPublicKeeperExternalSweepReportRoute: typeof ApiPublicKeeperExternalSweepReportRoute
  ApiPublicKeeperLogsRoute: typeof ApiPublicKeeperLogsRoute
  ApiPublicKeeperReportRoute: typeof ApiPublicKeeperReportRoute
  ApiPublicKeeperStuckTokensRoute: typeof ApiPublicKeeperStuckTokensRoute
  ApiPublicKeeperTokensRoute: typeof ApiPublicKeeperTokensRoute
  ApiPublicKeeperWorkflowLocksRoute: typeof ApiPublicKeeperWorkflowLocksRoute
  ApiPublicKeeperWorkflowReportRoute: typeof ApiPublicKeeperWorkflowReportRoute
  ApiPublicKeeperWorkflowsRoute: typeof ApiPublicKeeperWorkflowsRoute
  ApiPublicSolanaRpcRoute: typeof ApiPublicSolanaRpcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-fees': {
      id: '/route-fees'
      path: '/route-fees'
      fullPath: '/route-fees'
      preLoaderRoute: typeof RouteFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$id': {
      id: '/token/$id'
      path: '/token/$id'
      fullPath: '/token/$id'
      preLoaderRoute: typeof TokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-fees/$claimToken': {
      id: '/route-fees/$claimToken'
      path: '/$claimToken'
      fullPath: '/route-fees/$claimToken'
      preLoaderRoute: typeof RouteFeesClaimTokenRouteImport
      parentRoute: typeof RouteFeesRoute
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/keeper-logs': {
      id: '/admin/keeper-logs'
      path: '/admin/keeper-logs'
      fullPath: '/admin/keeper-logs'
      preLoaderRoute: typeof AdminKeeperLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi': {
      id: '/api/v1/openapi'
      path: '/api/v1/openapi'
      fullPath: '/api/v1/openapi'
      preLoaderRoute: typeof ApiV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/markets': {
      id: '/api/v1/markets'
      path: '/api/v1/markets'
      fullPath: '/api/v1/markets'
      preLoaderRoute: typeof ApiV1MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/launch': {
      id: '/api/v1/launch'
      path: '/api/v1/launch'
      fullPath: '/api/v1/launch'
      preLoaderRoute: typeof ApiV1LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reconcile-launches': {
      id: '/api/admin/reconcile-launches'
      path: '/api/admin/reconcile-launches'
      fullPath: '/api/admin/reconcile-launches'
      preLoaderRoute: typeof ApiAdminReconcileLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs_/$tokenId': {
      id: '/admin/logs_/$tokenId'
      path: '/admin/logs/$tokenId'
      fullPath: '/admin/logs/$tokenId'
      preLoaderRoute: typeof AdminLogsTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/keeper-logs_/$tokenId': {
      id: '/admin/keeper-logs_/$tokenId'
      path: '/admin/keeper-logs/$tokenId'
      fullPath: '/admin/keeper-logs/$tokenId'
      preLoaderRoute: typeof AdminKeeperLogsTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/launch/$tokenId': {
      id: '/api/v1/launch/$tokenId'
      path: '/$tokenId'
      fullPath: '/api/v1/launch/$tokenId'
      preLoaderRoute: typeof ApiV1LaunchTokenIdRouteImport
      parentRoute: typeof ApiV1LaunchRoute
    }
    '/api/public/solana/rpc': {
      id: '/api/public/solana/rpc'
      path: '/api/public/solana/rpc'
      fullPath: '/api/public/solana/rpc'
      preLoaderRoute: typeof ApiPublicSolanaRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/workflows': {
      id: '/api/public/keeper/workflows'
      path: '/api/public/keeper/workflows'
      fullPath: '/api/public/keeper/workflows'
      preLoaderRoute: typeof ApiPublicKeeperWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/workflow-report': {
      id: '/api/public/keeper/workflow-report'
      path: '/api/public/keeper/workflow-report'
      fullPath: '/api/public/keeper/workflow-report'
      preLoaderRoute: typeof ApiPublicKeeperWorkflowReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/workflow-locks': {
      id: '/api/public/keeper/workflow-locks'
      path: '/api/public/keeper/workflow-locks'
      fullPath: '/api/public/keeper/workflow-locks'
      preLoaderRoute: typeof ApiPublicKeeperWorkflowLocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/tokens': {
      id: '/api/public/keeper/tokens'
      path: '/api/public/keeper/tokens'
      fullPath: '/api/public/keeper/tokens'
      preLoaderRoute: typeof ApiPublicKeeperTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/stuck-tokens': {
      id: '/api/public/keeper/stuck-tokens'
      path: '/api/public/keeper/stuck-tokens'
      fullPath: '/api/public/keeper/stuck-tokens'
      preLoaderRoute: typeof ApiPublicKeeperStuckTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/report': {
      id: '/api/public/keeper/report'
      path: '/api/public/keeper/report'
      fullPath: '/api/public/keeper/report'
      preLoaderRoute: typeof ApiPublicKeeperReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/logs': {
      id: '/api/public/keeper/logs'
      path: '/api/public/keeper/logs'
      fullPath: '/api/public/keeper/logs'
      preLoaderRoute: typeof ApiPublicKeeperLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/external-sweep-report': {
      id: '/api/public/keeper/external-sweep-report'
      path: '/api/public/keeper/external-sweep-report'
      fullPath: '/api/public/keeper/external-sweep-report'
      preLoaderRoute: typeof ApiPublicKeeperExternalSweepReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/external-routers': {
      id: '/api/public/keeper/external-routers'
      path: '/api/public/keeper/external-routers'
      fullPath: '/api/public/keeper/external-routers'
      preLoaderRoute: typeof ApiPublicKeeperExternalRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keeper/external-router-seen': {
      id: '/api/public/keeper/external-router-seen'
      path: '/api/public/keeper/external-router-seen'
      fullPath: '/api/public/keeper/external-router-seen'
      preLoaderRoute: typeof ApiPublicKeeperExternalRouterSeenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/launch/$tokenId/metadata': {
      id: '/api/v1/launch/$tokenId/metadata'
      path: '/metadata'
      fullPath: '/api/v1/launch/$tokenId/metadata'
      preLoaderRoute: typeof ApiV1LaunchTokenIdMetadataRouteImport
      parentRoute: typeof ApiV1LaunchTokenIdRoute
    }
  }
}

interface RouteFeesRouteChildren {
  RouteFeesClaimTokenRoute: typeof RouteFeesClaimTokenRoute
}

const RouteFeesRouteChildren: RouteFeesRouteChildren = {
  RouteFeesClaimTokenRoute: RouteFeesClaimTokenRoute,
}

const RouteFeesRouteWithChildren = RouteFeesRoute._addFileChildren(
  RouteFeesRouteChildren,
)

interface ApiV1LaunchTokenIdRouteChildren {
  ApiV1LaunchTokenIdMetadataRoute: typeof ApiV1LaunchTokenIdMetadataRoute
}

const ApiV1LaunchTokenIdRouteChildren: ApiV1LaunchTokenIdRouteChildren = {
  ApiV1LaunchTokenIdMetadataRoute: ApiV1LaunchTokenIdMetadataRoute,
}

const ApiV1LaunchTokenIdRouteWithChildren =
  ApiV1LaunchTokenIdRoute._addFileChildren(ApiV1LaunchTokenIdRouteChildren)

interface ApiV1LaunchRouteChildren {
  ApiV1LaunchTokenIdRoute: typeof ApiV1LaunchTokenIdRouteWithChildren
}

const ApiV1LaunchRouteChildren: ApiV1LaunchRouteChildren = {
  ApiV1LaunchTokenIdRoute: ApiV1LaunchTokenIdRouteWithChildren,
}

const ApiV1LaunchRouteWithChildren = ApiV1LaunchRoute._addFileChildren(
  ApiV1LaunchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  DocsRoute: DocsRoute,
  HomeRoute: HomeRoute,
  LaunchRoute: LaunchRoute,
  PaperRoute: PaperRoute,
  RouteFeesRoute: RouteFeesRouteWithChildren,
  StatsRoute: StatsRoute,
  TokensRoute: TokensRoute,
  AdminKeeperLogsRoute: AdminKeeperLogsRoute,
  AdminLogsRoute: AdminLogsRoute,
  ApiDocsRoute: ApiDocsRoute,
  TokenIdRoute: TokenIdRoute,
  AdminKeeperLogsTokenIdRoute: AdminKeeperLogsTokenIdRoute,
  AdminLogsTokenIdRoute: AdminLogsTokenIdRoute,
  ApiAdminReconcileLaunchesRoute: ApiAdminReconcileLaunchesRoute,
  ApiV1LaunchRoute: ApiV1LaunchRouteWithChildren,
  ApiV1MarketsRoute: ApiV1MarketsRoute,
  ApiV1OpenapiRoute: ApiV1OpenapiRoute,
  ApiPublicKeeperExternalRouterSeenRoute:
    ApiPublicKeeperExternalRouterSeenRoute,
  ApiPublicKeeperExternalRoutersRoute: ApiPublicKeeperExternalRoutersRoute,
  ApiPublicKeeperExternalSweepReportRoute:
    ApiPublicKeeperExternalSweepReportRoute,
  ApiPublicKeeperLogsRoute: ApiPublicKeeperLogsRoute,
  ApiPublicKeeperReportRoute: ApiPublicKeeperReportRoute,
  ApiPublicKeeperStuckTokensRoute: ApiPublicKeeperStuckTokensRoute,
  ApiPublicKeeperTokensRoute: ApiPublicKeeperTokensRoute,
  ApiPublicKeeperWorkflowLocksRoute: ApiPublicKeeperWorkflowLocksRoute,
  ApiPublicKeeperWorkflowReportRoute: ApiPublicKeeperWorkflowReportRoute,
  ApiPublicKeeperWorkflowsRoute: ApiPublicKeeperWorkflowsRoute,
  ApiPublicSolanaRpcRoute: ApiPublicSolanaRpcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
